version: '3.8'

services:

  server:
    container_name: server
    image: somikhaylov/flask-k8s:v0.0.1
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: somikhaylov/postgres-k8s:v0.0.1
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    container_name: client
    image: somikhaylov/vue-k8s:v0.0.1
    build:
      context: ./services/client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
