version: '3.8'

services:

  postgres-micro:
    container_name: postgres-micro
    image: somikhaylov/postgres-micro:latest
    build:
      context: ./src/postgres-micro
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      microservices:

  flask-micro:
    container_name: flask-micro
    image: somikhaylov/flask-micro:latest
    build:
      context: ./src/flask-micro
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres-micro
    networks:
      microservices:

  vue-k8s:
    container_name: vue-micro
    image: somikhaylov/vue-micro:latest
    build:
      context: ./src/vue-micro
      dockerfile: Dockerfile
      args: 
        - http://localhost:5000
    ports:
      - 8080:8080
    depends_on:
      - flask-micro
    networks:
      microservices:

networks:
  microservices:
    name: microservices-network