apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.dnsName }}
    http:
      paths:
      - path: /books
        pathType: Prefix
        backend:
          service:
            name: flask
            port:
              number: 5000
