apiVersion: v1
kind: Service
metadata:
  name: postgres-micro
  labels:
    service: postgres-micro
spec:
  selector:
    service: postgres-micro
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: postgres-exporter
    port: 9187
    protocol: TCP
    targetPort: 9187