apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-micro
  labels:
    service: postgres-micro
spec:
  selector:
    matchLabels:
      service: postgres-micro
  endpoints:
  - port: postgres-exporter