apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: vue-micro
  name: vue-micro
spec:
  progressDeadlineSeconds: 2147483647
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vue-micro
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vue-micro
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: vue-micro
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
