apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue-micro-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.dnsName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vue-micro
            port:
              number: 8080
