apiVersion: v1
kind: Service
metadata:
  name: vue-micro
  labels:
    service: vue-micro
  name: vue-micro
spec:
  selector:
    app: vue-micro
  ports:
  - name: http
    port: 8080
    targetPort: 8080
